name: EAS Submit Only

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Check EAS Login Status
        run: eas whoami
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}

      - name: Submit latest iOS build to TestFlight
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}
          ASC_API_KEY_PATH: ./authkey.p8
          ASC_API_KEY_ISSUER_ID: ${{ secrets.ASC_API_KEY_ISSUER_ID }}
          ASC_API_KEY_ID: ${{ secrets.ASC_API_KEY_ID }}
        run: |
          eas submit --platform ios --profile production --non-interactive --latest

